# filter .bak data parsed 
bak_file:
    tables: 
        AspNetUsers:
            Noms: df_asp_net_users.iloc[:,1] 
        PLC1:
            Num_serie: df_plc1.iloc[0,5] 
        Tbl-Ref-BaseArticle:
            codeArticle: df_base_article.iloc[:,0]